<script>
    require([
        'jquery',
        'jquery/ui',
        'domReady!',
    ], function($){
        function getResponse(response) {
            var customerId = "<?= (string)$block->getCustomerId() ?>";
            $.ajax({
                method: "POST",
                url: "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
                dataType: "json",
                data: {
                    form_key: window.FORM_KEY,
                    customer: customerId,
                    fingerprint: response.bayonet_fingerprint_token
                }
            });
        }
    
        $(document).ready(function() {
            var moduleEnabled = "<?= (int)$block->getEnabled() ?>";
            var isCustomerLoggedIn = "<?= (int)$block->getCustomerIsLoggedIn() ?>"
            if (parseInt(moduleEnabled) === 1) {
                if (isCustomerLoggedIn) {
                    $.getScript('https://cdn.bayonet.io/fingerprinting-2.0.min.js', function() {
                        initBayonet();
                    });
                }
            }
    
            function initBayonet() {
                var apiKey = "<?= (string)$block->getApiKey() ?>";
                if (apiKey) {
                    _bayonet.init({
                        js_key: apiKey,
                        callback_function: 'getResponse'
                    });
                    _bayonet.track();
                }
            }
        });
    
        window.getResponse = getResponse;
    });
</script>
