<?php
/**
 * @var $block \Bayonet\BayonetAntiFraud\Block\Adminhtml\OrderEdit\Tab\View
 */
?>

<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?=$block->escapeHtml(__('Information for Bayonet Anti-Fraud')) ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <?= $block->getChildHtml(); ?>
        <tr>
            <th><?= $block->escapeHtml(__('ID of Order:')) ?></th>
            <td><?= $block->escapeHtml($block->getOrderIncrementId()); ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Bayonet Tracking ID:')) ?></th>
            <td><?= $block->escapeHtml($block->getTrackingId()); ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('API Call Status:')) ?></th>
            <td><?= $block->escapeHtml($block->getApiResponse()); ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Decision:')) ?></th>
            <td><?= $block->escapeHtml($block->getDecision()); ?></td>
        </tr>
        <tr>
            <th><?= $block->escapeHtml(__('Triggered Rules:')) ?></th>
            <td class="bayonet_order_info"><?= $block->escapeHtml($block->getRules()); ?></td>
        </tr>
        </tbody>
    </table>
</div>