<?php
/**
 * @var $block \Bayonet\BayonetAntiFraud\Block\Adminhtml\OrderEdit\Tab\View
 */
?>

<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Information for Bayonet Anti-Fraud') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Order ID:') ?></th>
            <td><?php echo $block->getOrderIncrementId(); ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Bayonet Tracking ID:') ?></th>
            <td><?php echo $block->getTrackingId(); ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('API Response:') ?></th>
            <td><?php echo $block->getApiResponse(); ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Decision:') ?></th>
            <td><?php echo $block->getDecision(); ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Triggered Rules:') ?></th>
            <td class="bayonet_order_info"><?php echo $block->getRules(); ?></td>
        </tr>
        </tbody>
    </table>
</div>